/*
 * File: app/view/episodeList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RC.view.episodeList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.episodelist',

    config: {
        store: 'MyJsonStore',
        itemTpl: [
            '<img src="{Image}" style="margin-right: 5px;" height="75px" align="left" /><div><b>{Title}</b></div><div style="font-size: 0.8em;">{Description}</div>'
        ],
        listeners: [
            {
                fn: 'onListItemTap',
                event: 'itemtap'
            },
            {
                fn: 'onListInitialize',
                event: 'initialize'
            }
        ]
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var episodeInfo = Ext.create('RC.view.EpisodeInfo'),
            main = Ext.getCmp('main'),
            episodeTitle = episodeInfo.getComponent('episodeTitle'),
            episodeDescription = episodeInfo.getComponent('episodeDescription'),
            playButton = Ext.ComponentQuery.query('#playButton')[0];


        if(record.data === main.episode) {
            playButton.setDisabled(true);
            playButton.setText('Playing');

        }
        playButton.episode = record.data;

        episodeTitle.setHtml('<b>'+record.data.Title+'</b>');
        episodeDescription.setHtml('<img src="'+record.data.Image+'" style="float:left;margin-right:5px;" width="100px" />'+record.data.Description);

        main.add(episodeInfo);
        episodeInfo.show();

    },

    onListInitialize: function(component, eOpts) {
        component.add({xtype: 'component', height: 80, scrollDock: 'bottom'});
    }

});