/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RC.view.Main', {
    extend: 'Ext.Container',

    requires: [
        'RC.view.episodeList',
        'RC.view.Player'
    ],

    config: {
        id: 'main',
        itemId: 'main',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Reader\'s Corner',
                items: [
                    {
                        xtype: 'container',
                        centered: false,
                        hidden: true,
                        html: '<img style="margin-top: -10px" src="img/bspr.png" height="50px" />'
                    }
                ]
            },
            {
                xtype: 'episodelist'
            },
            {
                xtype: 'player'
            }
        ]
    }

});