/*
 * File: app/view/Player.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RC.view.Player', {
    extend: 'Ext.Container',
    alias: 'widget.player',

    config: {
        bottom: 0,
        height: 80,
        hidden: true,
        itemId: 'playerControls',
        style: 'position: absolute; z-index: 1; background: rgb(255,255,255);',
        width: '100%',
        layout: {
            type: 'hbox'
        },
        showAnimation: {
            type: 'slide',
            direction: 'up'
        },
        items: [
            {
                xtype: 'container',
                height: 80,
                itemId: 'playPause',
                style: 'background: url(\'img/blank.png\') no-repeat; background-size: 80px 80px;',
                width: 80
            },
            {
                xtype: 'container',
                flex: 1,
                items: [
                    {
                        xtype: 'sliderfield',
                        docked: 'bottom',
                        height: 55,
                        itemId: 'episodeSlider',
                        style: 'background: rgba(255,255,255, 0.9);'
                    },
                    {
                        xtype: 'component',
                        html: '2:23',
                        itemId: 'timeElapsed',
                        margin: '5 0 0 5',
                        style: 'font-size: 0.8em;',
                        width: 80
                    },
                    {
                        xtype: 'component',
                        docked: 'right',
                        html: '-32:23',
                        itemId: 'timeRemaining',
                        margin: '5 5 0 0',
                        style: 'font-size: 0.8em;'
                    }
                ]
            }
        ]
    }

});