/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Episode'
    ],
    stores: [
        'Episodes'
    ],
    views: [
        'Main',
        'episodeList',
        'EpisodeInfo',
        'Player'
    ],
    controllers: [
        'EpisodeInfo',
        'Player'
    ],
    name: 'RC',

    launch: function() {
        soundManager.setup({
            url: 'swf/',
            preferFlash: false,
            onready: function() {
                console.log('soundmanager ready');

            }
        });
        Ext.create('RC.view.Main', {fullscreen: true});
    },

    setSliderValue: function(position, duration) {
        var sound = Ext.getCmp('main').sound,
            percent = parseInt(Math.floor((100 / sound.duration) * sound.currentTime), 10),
            slider = Ext.ComponentQuery.query('#episodeSlider')[0];

        slider.setValue(percent);
        //val = (100 / sound.duration) * sound.currentTime || 0;
    }

});
